import * as vscode from "vscode";
import * as path from "path";
import * as fs from "fs";
import { DiffResult } from "./gitService";

export class ReportGenerator {
  /**
   * 生成 .md 报告文件并自动打开
   * 返回文件路径
   */
  static async generate(
    workspaceRoot: string,
    diffResult: DiffResult,
    reviewContent: string,
    customOutputDir?: string
  ): Promise<string> {
    const now = new Date();
    const timestamp = now
      .toISOString()
      .replace(/[:.]/g, "-")
      .substring(0, 19);

    const fileName = `review-${diffResult.headBranch}-${timestamp}.md`;

    // 确定输出目录
    const outputDir = customOutputDir
      ? path.resolve(workspaceRoot, customOutputDir)
      : workspaceRoot;

    // 确保目录存在
    if (!fs.existsSync(outputDir)) {
      fs.mkdirSync(outputDir, { recursive: true });
    }

    const filePath = path.join(outputDir, fileName);

    // 构建完整报告
    const report = this.buildReportMarkdown(diffResult, reviewContent, timestamp);

    // 写入文件
    fs.writeFileSync(filePath, report, "utf-8");

    // 在编辑器中打开
    const doc = await vscode.workspace.openTextDocument(filePath);
    await vscode.window.showTextDocument(doc, { preview: false });

    return filePath;
  }

  /**
   * 构建完整的 Markdown 报告内容
   */
  private static buildReportMarkdown(
    diffResult: DiffResult,
    reviewContent: string,
    timestamp: string
  ): string {
    const { baseBranch, headBranch, fileDiffs, totalAdditions, totalDeletions } = diffResult;

    const fileList = fileDiffs
      .map(
        (f) =>
          `| \`${f.filePath}\` | +${f.additions} | -${f.deletions} |`
      )
      .join("\n");

    return `# Git AI Review Report

> Generated by **Git AI Review** plugin powered by DeepSeek

## 基本信息

| 项目 | 值 |
|------|-----|
| **基准分支** | \`${baseBranch}\` |
| **当前分支** | \`${headBranch}\` |
| **生成时间** | ${timestamp} |
| **变更文件数** | ${fileDiffs.length} |
| **新增行数** | +${totalAdditions} |
| **删除行数** | -${totalDeletions} |

## 变更文件列表

| 文件 | 新增 | 删除 |
|------|------|------|
${fileList}

---

${reviewContent}

---

*本报告由 [Git AI Review](https://github.com/tzy168/git-ai-review) 插件自动生成，仅供参考。*
`;
  }
}
